routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::prefix(\App\Http\Localization\Localization::getCurrentLocale())->group(function(){

    Route::get('/', [\App\Http\Controllers\HomeController::class,'index'])->name('index');

    Route::get('universities',[\App\Http\Controllers\UniversityController::class,'index'])->name('universities');

    Route::get('companies',[\App\Http\Controllers\HomeController::class,'companies'])->name('companies');

    Route::get('courses',[\App\Http\Controllers\HomeController::class,'courses'])->name('courses');

    Route::get('course/{slug?}',[\App\Http\Controllers\HomeController::class,'course'])->name('course');

    Route::get('about',[\App\Http\Controllers\HomeController::class,'about'])->name('about');

    Route::get('jobs',[\App\Http\Controllers\HomeController::class,'jobs'])->name('jobs');

    Route::get('contact',[\App\Http\Controllers\HomeController::class,'contact'])->name('contact');

    Route::get('register',[\App\Http\Controllers\HomeController::class,'register'])->name('register');

    Route::get('login',[\App\Http\Controllers\HomeController::class,'login'])->name('login');

    Route::post('login',[\App\Http\Controllers\HomeController::class,'signIn'])->name('sign-in');

    Route::post('register',[\App\Http\Controllers\HomeController::class,'registerStore'])->name('register.store');

    Route::get('logout',[\App\Http\Controllers\HomeController::class,'logout'])->name('logout');

    Route::get('/teacher/settings',[\App\Http\Controllers\HomeController::class,'teacher_settings'])->name('teacher.settings');

    Route::get('/student/settings',[\App\Http\Controllers\HomeController::class,'student_settings'])->name('student.settings');

});




Route::name('admin.')->prefix('admin')->group(function(){

    Route::get('authentication/login',[\App\Http\Controllers\Admin\LoginController::class,'login']);
    Route::post('authentication/login',[\App\Http\Controllers\Admin\LoginController::class,'auth'])->name('login');

    Route::middleware(['admin'])->group(function (){

        Route::get('dashboard',[\App\Http\Controllers\Admin\LoginController::class,'dashboard'])->name('dashboard');
        Route::get('logout',[\App\Http\Controllers\Admin\LoginController::class,'logout'])->name('logout');

        Route::resources([

            'course'        => \App\Http\Controllers\Admin\CourseController::class,
            'partner'       => \App\Http\Controllers\Admin\PartnerController::class,
            'university'    => \App\Http\Controllers\Admin\UniversityController::class,
            'company'       => \App\Http\Controllers\Admin\CompanyController::class,
            'level'         => \App\Http\Controllers\Admin\LevelController::class,
            'payment-type'  => \App\Http\Controllers\Admin\PaymentTypeController::class,
            'language'      => \App\Http\Controllers\Admin\LanguageController::class,
            'speaker'       => \App\Http\Controllers\Admin\SpeakerController::class,



        ]);


    });

});

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no">
    <title>Admin Login | Imkan.az </title>
    <link rel="icon" type="image/x-icon" href="{{asset('assets/admin/img/favicon.ico')}}"/>
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
    <link href="{{asset('assets/admin/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/admin/css/plugins.css')}}" rel="stylesheet" type="text/css" />
    <link href="{{asset('assets/admin/css/authentication/form-2.css')}}" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <link rel="stylesheet" type="text/css" href="{{asset('assets/admin/css/forms/theme-checkbox-radio.css')}}">
    <link rel="stylesheet" type="text/css" href="{{asset('assets/admin/css/forms/switches.css')}}">
</head>
<body class="form">


<div class="form-container outer">
    <div class="form-form">
        <div class="form-form-wrap">
            <div class="form-container">
                <div class="form-content">
                    <h1 class="">Sign In</h1>
                    <p class="">Log in to your account to continue.</p>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <div>{{ $error }}</div>
                                @endforeach
                            </ul>
                        </div>
                    @endif

                    @if(session()->has('error'))
                        <div class="alert alert-danger">{{session()->get('error')}}</div>
                    @endif

                    <form class="text-left" action="{{route('admin.login')}}" method="POST">
                        <div class="form">
                            @csrf

                            <div id="username-field" class="field-wrapper input">
                                <label for="username">EMAIL</label>
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-user"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path><circle cx="12" cy="7" r="4"></circle></svg>
                                <input id="username" name="email" type="email" class="form-control" placeholder="e.g johndoe@mail.ru">
                            </div>

                            <div id="password-field" class="field-wrapper input mb-2">
                                <div class="d-flex justify-content-between">
                                    <label for="password">PASSWORD</label>
                                </div>
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-lock"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"></rect><path d="M7 11V7a5 5 0 0 1 10 0v4"></path></svg>
                                <input id="password" name="password" type="password" class="form-control" placeholder="Password">
                                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" id="toggle-password" class="feather feather-eye"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"></path><circle cx="12" cy="12" r="3"></circle></svg>
                            </div>

                            <div class="d-sm-flex justify-content-between">
                                <div class="field-wrapper">
                                    <button type="submit" class="btn btn-primary">Log In</button>
                                </div>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>


<!-- BEGIN GLOBAL MANDATORY SCRIPTS -->
<script src="{{asset('assets/admin/js/libs/jquery-3.1.1.min.js')}}"></script>
<script src="{{asset('assets/admin/bootstrap/js/popper.min.js')}}"></script>
<script src="{{asset('assets/admin/bootstrap/js/bootstrap.min.js')}}"></script>
<!-- END GLOBAL MANDATORY SCRIPTS -->

<script src="{{asset('assets/admin/js/authentication/form-2.js')}}"></script>

</body>
</html>