routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/




Route::prefix(\App\Http\Localization\Localization::getCurrentLocale())->group(function(){

    Route::get('/', [\App\Http\Controllers\HomeController::class,'index'])->name('index');

    Route::get('universities',[\App\Http\Controllers\UniversityController::class,'index'])->name('universities');

    Route::get('companies',[\App\Http\Controllers\HomeController::class,'companies'])->name('companies');

    Route::get('courses',[\App\Http\Controllers\HomeController::class,'courses'])->name('courses');

    Route::get('course/{slug?}',[\App\Http\Controllers\HomeController::class,'course'])->name('course');

    Route::get('about',[\App\Http\Controllers\HomeController::class,'about'])->name('about');

    Route::get('jobs',[\App\Http\Controllers\HomeController::class,'jobs'])->name('jobs');

    Route::get('contact',[\App\Http\Controllers\HomeController::class,'contact'])->name('contact');

    Route::get('register',[\App\Http\Controllers\HomeController::class,'register'])->name('register');

    Route::get('login',[\App\Http\Controllers\HomeController::class,'login'])->name('login');

    Route::post('login',[\App\Http\Controllers\HomeController::class,'signIn'])->name('sign-in');

    Route::post('register',[\App\Http\Controllers\HomeController::class,'registerStore'])->name('register.store');

    Route::get('logout',[\App\Http\Controllers\HomeController::class,'logout'])->name('logout');

    Route::get('/teacher/settings',[\App\Http\Controllers\HomeController::class,'teacher_settings'])->name('teacher.settings');

    Route::get('/student/settings',[\App\Http\Controllers\HomeController::class,'student_settings'])->name('student.settings');

});




Route::name('admin.')->prefix('admin')->group(function(){

    Route::get('authentication/login',[\App\Http\Controllers\Admin\LoginController::class,'login']);
    Route::post('authentication/login',[\App\Http\Controllers\Admin\LoginController::class,'auth'])->name('login');

    Route::middleware(['admin'])->group(function (){

        Route::get('dashboard',[\App\Http\Controllers\Admin\LoginController::class,'dashboard'])->name('dashboard');
        Route::get('logout',[\App\Http\Controllers\Admin\LoginController::class,'logout'])->name('logout');

        Route::resources([

            'course'        => \App\Http\Controllers\Admin\CourseController::class,
            'partner'       => \App\Http\Controllers\Admin\PartnerController::class,
            'university'    => \App\Http\Controllers\Admin\UniversityController::class,
            'company'       => \App\Http\Controllers\Admin\CompanyController::class,
            'level'         => \App\Http\Controllers\Admin\LevelController::class,
            'payment-type'  => \App\Http\Controllers\Admin\PaymentTypeController::class,
            'language'      => \App\Http\Controllers\Admin\LanguageController::class,
            'speaker'       => \App\Http\Controllers\Admin\SpeakerController::class,



        ]);


    });

});

app/Models/Course.php
<?php

namespace App\Models;

use App\Models\Translations\CourseTranslation;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class Course extends Model
{
    use HasFactory;

    protected $guarded = [];

    public function translations(){
        return $this->hasMany(CourseTranslation::class)
            ->rightJoin('languages',function ($join){
                $join->on('languages.locale','course_translations.locale');
            })
            ->orWhereNull('course_translations.course_id')
            ->where('languages.active',1)->select('course_translations.*','languages.locale');
    }


    public function translation(){
        return $this->hasOne(CourseTranslation::class)->where('locale',App::getLocale());
    }

    public function level(){
        return $this->belongsTo(Level::class);
    }

    public function payment(){
        return $this->belongsTo(Payment::class);
    }

}

app/Http/Controllers/Admin/CourseController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Localization\Localization;
use App\Models\Course;
use App\Models\Translations\CourseTranslation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Response;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

class CourseController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     */
    public function index()
    {
        $courses = Course::with(['translation'])->get()->filter(function($translations){
            if($translations->translation != null){
                return $translations;
            }
        });
        return view('admin.course.index',['courses' => $courses]);
    }

    /**
     * Show the form for creating a new resource.
     *
     */
    public function create()
    {
        return view('admin.course.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     */
    public function store(Request $request)
    {
        $request->validate([
            'name.*'            => 'required|max:255',
            'about.*'           => 'required',
            'description.*'     => 'required',
            'requirement.*'     => 'required',
            'price'             => 'required|numeric',
            'image'             => 'required|mimes:jpeg,png,jpg|max:2048',
            'level_id'          => 'required|exists:levels,id',
            'payment_id'        => 'required|exists:payments,id',
            'duration'          => 'required|integer|between:1,5'
        ]);


        $course = Course::create([
            'price'         => $request->price,
            'image'         => Storage::putFile('public/course',$request->file('image')),
            'duration_id'   => $request->duration,
            'level_id'      => $request->level_id,
            'payment_id'    => $request->payment_id
        ]);

        $data = [];

        foreach ($request->name as $locale => $name){
            $data[] = [
                'name'          => $name,
                'about'         => $request->about[$locale],
                'description'   => $request->description[$locale],
                'requirement'   => $request->requirement[$locale],
                'locale'        => $locale,
                'slug'          => Str::slug($name)
            ];
        }

        $course->translations()->createMany($data);
        return redirect()->route('admin.course.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     */
    public function edit($id)
    {
        $course = Course::findOrFail($id);
        return view('admin.course.edit',['course' => $course]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'name.*'            => 'required|max:255',
            'about.*'           => 'required',
            'description.*'     => 'required',
            'requirement.*'     => 'required',
            'price'             => 'required|numeric',
            'image'             => 'mimes:jpeg,png,jpg|max:2048',
            'level_id'          => 'required|exists:levels,id',
            'payment_id'        => 'required|exists:payments,id',
            'duration'          => 'required|integer|between:1,5'
        ]);


        $course = Course::findOrFail($id);

        $course->price      = $request->price;
        $course->level_id   = $request->level_id;

        $course->payment_id = $request->payment_id;
        $course->duration_id= $request->duration;

        if($request->hasFile('image')){
            Storage::delete($course->image);
            $course->image  = Storage::putFile('public/course',$request->file('image'));
        }
        $course->save();


        $data = [];
        foreach ($request->name as $locale => $name){
            $data[] = [
                'name'          => $name,
                'about'         => $request->about[$locale],
                'description'   => $request->description[$locale],
                'requirement'   => $request->requirement[$locale],
                'locale'        => $locale,
                'slug'          => Str::slug($name)
            ];
        }

        $course->translations()->delete();
        $course->translations()->createMany($data);
        return redirect()->route('admin.course.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     */
    public function destroy($id)
    {
        Course::destroy($id);
        return response()->json(['success' => true]);
    }
}

resources/views/admin/course/create.blade.php
@extends('layouts.admin')

@section('title','Course Create')

@section('css-app')

    <link href="{{asset('assets/admin/css/loader.css')}}" rel="stylesheet" type="text/css"/>
    <script src="{{asset('assets/admin/js/loader.js')}}"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
    <link href="/assets/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/admin/css/plugins.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->

    <!--  BEGIN CUSTOM STYLE FILE  -->
    <link href="/assets/admin/css/scrollspyNav.css" rel="stylesheet" type="text/css" />
    {{--<link rel="stylesheet" type="text/css" href="/assets/admin/plugins/bootstrap-select/bootstrap-select.min.css">--}}
    <link href="/assets/admin/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
    <link href="/assets/admin/plugins/file-upload/file-upload-with-preview.min.css" rel="stylesheet" type="text/css" />


@endsection


@section('content')

    <div id="content" class="main-content">
        <div class="container m-auto">
            <div class="container">

                <div class="col-lg-12 col-12 layout-spacing">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-header">
                            <div class="row">
                                <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                    <h4>Create Course</h4>
                                </div>
                            </div>
                        </div>

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="widget-content widget-content-area border-tab">

                            <ul class="nav nav-tabs mt-3" id="border-tabs" role="tablist">
                                @foreach($languages as $language)
                                    <li class="nav-item">
                                        <a class="nav-link {{$loop->index == 0 ? 'active' : ''}}" id="border-home-tab" data-toggle="tab" href="#lang-{{$language->locale}}" role="tab" aria-controls="border-home" aria-selected="true"><img width="30px;" src="/assets/admin/lang/{{$language->locale}}.png"> {{strtoupper($language->code)}}</a>
                                    </li>
                                @endforeach

                            </ul>
                            <form action="{{route('admin.course.store')}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                <div class="tab-content mb-4" id="border-tabsContent">

                                    @foreach($languages as $language)
                                        <div class="tab-pane fade {{$loop->index == 0 ? 'show active' : ''}}" id="lang-{{$language->locale}}" role="tabpanel" aria-labelledby="border-home-tab">
                                            <label for="course-name">Name ({{$language->locale}})</label>
                                            <input title="" type="text" value="{{old('name'.$language->locale)}}" class="form-control" id="course-name" name="name[{{$language->locale}}]" required>
                                            <label for="about">About ({{$language->locale}})</label>
                                            <textarea class="form-control" name="about[{{$language->locale}}]" id="about" cols="30" rows="10">{{old('about'.$language->locale)}}</textarea>
                                            <label for="description">Description ({{$language->locale}})</label>
                                            <textarea class="form-control" name="description[{{$language->locale}}]" id="description" cols="30" rows="10">{{old('description'.$language->locale)}}</textarea>
                                            <label for="requirement">Requirement ({{$language->locale}})</label>
                                            <textarea class="form-control" name="requirement[{{$language->locale}}]" id="requirement" cols="30" rows="10">{{old('requirement'.$language->locale)}}</textarea>
                                        </div>
                                    @endforeach

                                    <div class="form-group mt-9">
                                        <label for="price">Price</label>
                                        <input type="number" id="price" name="price" value="{{old('price')}}" class="form-control" required>
                                    </div>

                                    <div class="form-group mt-9">
                                        <label for="level">Level</label>
                                        <select name="level_id" id="level" class="form-control">
                                            <option value=""></option>
                                            @foreach(\App\Models\Level::all() as $level)
                                                <option value="{{$level->id}}">{{$level->translation->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="form-group mt-9">
                                        <label for="payment_id">Payment Type</label>
                                        <select name="payment_id" id="payment_id" class="form-control">
                                            <option value=""></option>
                                            @foreach(\App\Models\Payment::all() as $payment)
                                                <option value="{{$payment->id}}">{{$payment->translation->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="form-group mt-9">
                                        <label for="duration">Duration</label>
                                        <select name="duration" id="duration" class="form-control">
                                            <option value=""></option>
                                            @foreach(range(1,5) as $duration)
                                                <option value="{{$duration}}"> {{$duration}} hours</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="widget-content widget-content-area">
                                        <div class="custom-file-container" data-upload-id="myFirstImage">
                                            <label>Upload (Single File) <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">x</a></label>
                                            <label class="custom-file-container__custom-file" >
                                                <input type="file" class="custom-file-container__custom-file__custom-file-input" name="image" accept="image/*">
                                                <span class="custom-file-container__custom-file__custom-file-control"></span>
                                            </label>
                                            <div class="custom-file-container__image-preview"></div>
                                        </div>
                                    </div>
                                    <button type="submit" class="mt-4 btn btn-primary float-right">Create</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

@endsection


@section('js')

    <script src="/assets/admin/js/libs/jquery-3.1.1.min.js"></script>
    <script src="/assets/admin/bootstrap/js/popper.min.js"></script>
    <script src="/assets/admin/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/admin/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="/assets/admin/js/app.js"></script>

    <script>
        $(document).ready(function() {
            App.init();
        });
    </script>
    <script src="/assets/admin/plugins/highlight/highlight.pack.js"></script>
    <script src="/assets/admin/js/custom.js"></script>
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <script src="/assets/admin/js/scrollspyNav.js"></script>
    {{-- <script src="/assets/admin/plugins/bootstrap-select/bootstrap-select.min.js"></script>--}}
    <script src="/assets/admin/plugins/file-upload/file-upload-with-preview.min.js"></script>

    <script>
        var firstUpload = new FileUploadWithPreview('myFirstImage');
    </script>

@endsection

resources/views/admin/course/edit.blade.php
@extends('layouts.admin')

@section('title','Course Create')

@section('css-app')

    <link href="{{asset('assets/admin/css/loader.css')}}" rel="stylesheet" type="text/css"/>
    <script src="{{asset('assets/admin/js/loader.js')}}"></script>
    <link href="https://fonts.googleapis.com/css?family=Nunito:400,600,700" rel="stylesheet">
    <link href="/assets/admin/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/assets/admin/css/plugins.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->

    <!--  BEGIN CUSTOM STYLE FILE  -->
    <link href="/assets/admin/css/scrollspyNav.css" rel="stylesheet" type="text/css" />
    {{--<link rel="stylesheet" type="text/css" href="/assets/admin/plugins/bootstrap-select/bootstrap-select.min.css">--}}
    <link href="/assets/admin/css/components/tabs-accordian/custom-tabs.css" rel="stylesheet" type="text/css" />
    <link href="/assets/admin/plugins/file-upload/file-upload-with-preview.min.css" rel="stylesheet" type="text/css" />


@endsection


@section('content')

    <div id="content" class="main-content">
        <div class="container m-auto">
            <div class="container">

                <div class="col-lg-12 col-12 layout-spacing">
                    <div class="statbox widget box box-shadow">
                        <div class="widget-header">
                            <div class="row">
                                <div class="col-xl-12 col-md-12 col-sm-12 col-12">
                                    <h4>Create Course</h4>
                                </div>
                            </div>
                        </div>

                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div>
                        @endif
                        <div class="widget-content widget-content-area border-tab">

                            <ul class="nav nav-tabs mt-3" id="border-tabs" role="tablist">
                                @foreach($languages as $language)
                                    <li class="nav-item">
                                        <a class="nav-link {{$loop->index == 0 ? 'active' : ''}}" id="border-home-tab" data-toggle="tab" href="#lang-{{$language->locale}}" role="tab" aria-controls="border-home" aria-selected="true"><img width="30px;" src="/assets/admin/lang/{{$language->locale}}.png"> {{strtoupper($language->code)}}</a>
                                    </li>
                                @endforeach

                            </ul>
                            <form action="{{route('admin.course.update',['course' => $course->id])}}" method="POST" enctype="multipart/form-data">
                                @csrf
                                @method('PUT')
                                <div class="tab-content mb-4" id="border-tabsContent">

                                    @foreach($course->translations as $translation)

                                        <div class="tab-pane fade {{$loop->index == 0 ? 'show active' : ''}}" id="lang-{{$translation->locale}}" role="tabpanel" aria-labelledby="border-home-tab">

                                            <label for="course-name">Name ({{$translation->locale}})</label>
                                            <input title="" type="text" value="{{$translation->name}}" class="form-control" id="course-name" name="name[{{$translation->locale}}]" required>

                                            <label for="about">About ({{$translation->locale}})</label>
                                            <textarea class="form-control" name="about[{{$translation->locale}}]" id="about" cols="30" rows="10">{{$translation->about}}</textarea>

                                            <label for="description">Description ({{$translation->locale}})</label>
                                            <textarea class="form-control" name="description[{{$translation->locale}}]" id="description" cols="30" rows="10">{{$translation->description}}</textarea>

                                            <label for="requirement">Requirement ({{$translation->locale}})</label>
                                            <textarea class="form-control" name="requirement[{{$translation->locale}}]" id="requirement" cols="30" rows="10">{{$translation->requirement}}</textarea>
                                        </div>

                                    @endforeach

                                    <div class="form-group mt-9 p-0">
                                        <label for="price">Price</label>
                                        <input type="text" id="price" name="price" value="{{$course->price}}" class="form-control" required>
                                    </div>

                                    <div class="form-group mt-9">
                                        <label for="level">Level</label>
                                        <select name="level_id" id="level" class="form-control">
                                            <option value=""></option>
                                            @foreach(\App\Models\Level::all() as $level)
                                                <option value="{{$level->id}}" @if($level->id == $course->level_id) selected @endif>{{$level->translation->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="form-group mt-9">
                                        <label for="payment_id">Payment Type</label>
                                        <select name="payment_id" id="payment_id" class="form-control">
                                            <option value=""></option>
                                            @foreach(\App\Models\Payment::all() as $payment)
                                                <option value="{{$payment->id}}" @if($payment->id == $course->payment_id) selected @endif>{{$payment->translation->name}}</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="form-group mt-9">
                                        <label for="duration">Duration</label>
                                        <select name="duration" id="duration" class="form-control">
                                            <option value=""></option>
                                            @foreach(range(1,5) as $duration)
                                                <option value="{{$duration}}" @if($duration == $course->duration_id) selected @endif> {{$duration}} Month</option>
                                            @endforeach
                                        </select>
                                    </div>

                                    <div class="widget-content widget-content-area">
                                        <div class="custom-file-container" data-upload-id="myFirstImage">
                                            <label>Upload (Single File) <a href="javascript:void(0)" class="custom-file-container__image-clear" title="Clear Image">x</a></label>
                                            <label class="custom-file-container__custom-file" >
                                                <input type="file" class="custom-file-container__custom-file__custom-file-input" name="image" accept="image/*">
                                                <span class="custom-file-container__custom-file__custom-file-control"></span>
                                            </label>
                                            <div class="custom-file-container__image-preview"></div>
                                        </div>
                                    </div>
                                    <button type="submit" class="mt-4 btn btn-primary float-right">Update</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

@endsection


@section('js')

    <script src="/assets/admin/js/libs/jquery-3.1.1.min.js"></script>
    <script src="/assets/admin/bootstrap/js/popper.min.js"></script>
    <script src="/assets/admin/bootstrap/js/bootstrap.min.js"></script>
    <script src="/assets/admin/plugins/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="/assets/admin/js/app.js"></script>

    <script>
        $(document).ready(function() {
            App.init();
        });
    </script>
    <script src="/assets/admin/plugins/highlight/highlight.pack.js"></script>
    <script src="/assets/admin/js/custom.js"></script>
    <!-- END GLOBAL MANDATORY SCRIPTS -->
    <script src="/assets/admin/js/scrollspyNav.js"></script>
    {{-- <script src="/assets/admin/plugins/bootstrap-select/bootstrap-select.min.js"></script>--}}
    <script src="/assets/admin/plugins/file-upload/file-upload-with-preview.min.js"></script>

    <script>
        var firstUpload = new FileUploadWithPreview('myFirstImage');
    </script>

@endsection